### PR TITLE
Fix WebOutlook domain

### PR DESCRIPTION
**Pull request by gulios**
## Context and Purposes

WebOutlook stopped working on
https://outlook.live.com domain
It redirects to main join live page instead of calendar.

I see that https://outlook.office.com works fine

### CODE REVIEW

**Comment by gulios** [comment]
Can we merge this ASAP please?

**Comment by lptn** [comment]
@gulios 
I just checked: it works on https://outlook.live.com (at lest in my country). Probably these URLs are country-specific, feel free to create your own Generator and use it

**Comment by gulios** [comment]
very strange because our customers reported it from many countries...
Anyway i'll write Generator and create pull request.

**Comment by lptn** [comment]
@gulios 
Can you please provide a list of countries? We need to collect more info about this case to make a proper decision.

**Comment by gulios** [comment]
For example GB or me from PL and others but now hard to find every task.
It just stopped working and redirects to "main" page of their page not to calendar stuff.
Changing it to https://outlook.office.com works fine and direct to calendar correctly.

**Comment by gulios** [comment]
same thing when i'm connected to VPN USA

You can see that links generated via lib

doesn't work - redirects to 
https://outlook.live.com/calendar/deeplink/compose?path=/calendar/action/compose&rru=addevent&startdt=2021-08-12T09:32:32Z&enddt=2021-08-12T10:17:32Z&subject=outloooookkkkk&body=Room%26%2332%3BID%3A%26%2332%3B252-691-050


works fine and showing calendar
https://outlook.office.com/calendar/deeplink/compose?path=/calendar/action/compose&rru=addevent&startdt=2021-08-12T09:32:32Z&enddt=2021-08-12T10:17:32Z&subject=outloooookkkkk&body=Room%26%2332%3BID%3A%26%2332%3B252-691-050

**Comment by gulios** [comment]
this is url after click on first link

https://outlook.live.com/owa/?path=%2fcalendar%2faction%2fcompose&rru=addevent&state=1&redirectTo=aHR0cHM6Ly9vdXRsb29rLmxpdmUuY29tL2NhbGVuZGFyL2RlZXBsaW5rL2NvbXBvc2UvP3BhdGg9JTJmY2FsZW5kYXIlMmZhY3Rpb24lMmZjb21wb3NlJnJydT1hZGRldmVudCZzdGFydGR0PTIwMjEtMDgtMTJUMDklM2EzMiUzYTMyWiZlbmRkdD0yMDIxLTA4LTEyVDEwJTNhMTclM2EzMlomc3ViamVjdD1vdXRsb29vb29ra2trayZib2R5PVJvb20lMjYlMjMzMiUzYklEJTNhJTI2JTIzMzIlM2IyNTItNjkxLTA1MA

and see this
Screenshot 2021-08-18 at 00 23 12

**Comment by lptn** [comment]
thanks, @gulios !
have you tested it on incognito mode?

**Comment by gulios** [comment]
yes, in private mode same behaviour

**Comment by lptn** [comment]
## incognito mode
### outlook.live.com

https://outlook.live.com/calendar/0/deeplink/compose?path=/calendar/action/compose&rru=addevent&startdt=2020-12-31T19:30:00Z&enddt=2020-12-31T22:30:00Z&subject=Birthday&body=With%20clowns%20and%20stuff&location=North%20Pole

shows landing page  (https://user-images.githubusercontent.com/14802005/129808539-7235d2c7-5705-4798-9482-08b9e3d59dbc.png)

### outlook.office.com

https://outlook.office.com/calendar/0/deeplink/compose?path=/calendar/action/compose&rru=addevent&startdt=2020-12-31T19:30:00Z&enddt=2020-12-31T22:30:00Z&subject=Birthday&body=With%20clowns%20and%20stuff&location=North%20Pole

shows login form

but after successful login, it redirects to https://outlook.live.com/mail/0/inbox (without adding an event to a calendar)


__________

Based on results of the test, It seems like outlook.live.com still is the main domain, at least of personal MS accounts:

image

**Comment by gulios** [comment]
image

we've tested it on couple of account and it doesn't work.
Even it opens (only on new macOS Montrey) it doesn't show calendar to choose etc

Only second link works for all with different domain.

Please let me know do you plan to change it or i have to add new generator for different link or maybe better add some property to change only domain?
Thank you.

**Pull request closed without merging**
