### PR TITLE
Add DTSTAMP to ICS generator, also use UTC timestamps instead of defining timezone

### PR DESCRIPTION
**Pull request by wxactly**
## Context and Purposes

This PR intends to fix Daylight Savings Time issues reported in #119 and #73.

This code originated in PR #140 (thanks @kodie) and was rerolled so that it now applies cleanly to version 1.8

### CODE REVIEW

**Review by lptn — APPROVED** [review]
Thanks @wxactly, looks good to me! 🚀

**Review by lptn — CHANGES_REQUESTED** [review]
failing tests

**Comment by wxactly** [comment]
No prob @lptn - I think I updated those properly, let me know how that looks!

**Comment by lptn** [comment]
thanks!

**Pull request merged**
