### PR TITLE
feat: ics as file

### PR DESCRIPTION
**Pull request by atymic**
## Context and Purposes

Sometimes, we want to be able to download a file rather than embedding a base64 link.
I used the existing options but would be open to doing it a different way if prefered.

### CODE REVIEW

**Comment by UksusoFF** [comment]
Looks at: https://github.com/spatie/calendar-links/pull/139

PR was closed. Any way to merge it?

@alies-dev @freekmurze

**Comment by alies-dev** [comment]
Hey 
@atymic 
@UksusoFF

Thank you a lot for your patience. A saw few PRs here, all of them tried to add more functionality to ICS generator by adding more options to the `$options` argument.  There are a few types of problems:
 - violation of package principles (see the main readme)
 - trying to make ICS really big and complex. This package doesn't have a goal to be a comprehensive ICS generator, it's made to support basic ICS rules, also available in other generators. For advanced users, this package supports custom generators that you can use by calling with `\Spatie\CalendarLinks\Link::formatWith()`
 - mixing ICS components with presentation logic


This particular PR has the issue # 3. Today I found a time to solve it and created another PR https://github.com/spatie/calendar-links/pull/185, can you please review it guys and leave your feedback? Will it solve your goals?

**Review by alies-dev — CHANGES_REQUESTED** [review]
mixing ICS components and presentation logic, see https://github.com/spatie/calendar-links/pull/174#issuecomment-1911703737 for details.

**Comment by UksusoFF** [comment]
@alies-dev 
Yep, https://github.com/spatie/calendar-links/pull/185 is great.

**Comment by atymic** [comment]
I will close this PR in favour of #185

**Pull request closed without merging**
