### PR TITLE
Fixed #148 fix space convert for outlook and office365

### LINKED ISSUE #148: Support description field adding HTML content.
When adding content using Microsoft calendar, you can add hyperlinks and images in the description field. I'm not sure it can be added in any other way, but if it is supported, need to add it in the test case. https://github.com/spatie/calendar-links/blob/master/tests/TestCase.php

In office.com's case, this line invalidates the HTML code that could otherwise be added (the tag a) to Office.com.
Lost HTML code ( tag a, tag img): 
```
$url .= '&body='.urlencode($this->sanitizeText($link->description));
```
https://github.com/spatie/calendar-links/pull/115/files#diff-52bc3e89d42d67ff8ce6574eae714190994c30e6f602250bab90d03f634f3c6bR40

https://github.com/spatie/calendar-links/blob/master/src/Generators/WebOffice.php#L40

Related:
Accented characters lost in Outlook #117

### PR DESCRIPTION
**Pull request by dravenk**
## Context and Purposes

Fixes #148

### CODE REVIEW

**Comment by dravenk** [comment]
Before. The tag link and tag image are broken.
148-bug

Bug fixed.
fix-148

**Comment by dravenk** [comment]
@lptn Hi. I've been using this MR in production for a few months and it's working fine. This MR contains test cases and should be usable.

**Comment by dravenk** [comment]
I only use outlook in my production environment.

**Review by lptn — APPROVED** [review]
thanks for the contribution,  @dravenk, approving 🚀

**Pull request merged**
