### PR TITLE
The "Z" in the URL is changing the original time to google calendar

### PR DESCRIPTION
**Pull request by ctoveloz**

### CODE REVIEW

**Comment by lptn** [comment]
Hey  @ctoveloz  

thanks for your contribution! Can you please elaborate your changes please? Have you tested it with UTC and non-UTC events?

**Comment by ctoveloz** [comment]
Hi @lptn ,

when generating the URL with "Z" it changes the time set in Google Calendar a example:

Actual with the "Z"
image
`https://calendar.google.com/calendar/u/0/r/eventedit?dates=20210629T000000Z/20210629T200000Z&text=Visual`

without the Z
image
`https://calendar.google.com/calendar/u/0/r/eventedit?dates=20210629T000000/20210629T200000&text=Visual`

I don't know what exactly happens with google calendar, but this way it showed the event correctly, another thing in your example in the README the url is also without the "Z".

**Comment by lptn** [comment]
@ctoveloz 
what is the date’s timezone you use when create DateTime objects?

**Comment by lptn** [comment]
hey @ctoveloz

what is the date’s timezone you use when create DateTime objects?


I need your answer, or we have to close this PR.

**Pull request closed without merging**
