### PR TITLE
Updated calendar link for Yahoo.

### PR DESCRIPTION
**Pull request by mukeshsah08**
Correct event details are not visible for Yahoo while registering the event.

### CODE REVIEW

**Comment by lptn** [comment]
Hey @mukeshsah08

Great work, pls fix tests and we are ready to merge and release it 👍

**Comment by mukeshsah08** [comment]
@lptn Please review. Thanks!

**Review by lptn — COMMENTED** [review]
Great work, @mukeshsah08! 2 latest questions:

1. Have you tested how yahoo works with allDay events? – You have removed a hack, don't we need it anymore?
2. I see you use lowercase for `in_loc` - does it work as expected?

**Comment by mukeshsah08** [comment]
> Great work, @mukeshsah08! 2 latest questions:
> 
> 1. Have you tested how yahoo works with allDay events? – You have removed a hack, don't we need it anymore?
Currently Yahoo does not support allDay feature since they have removed dur, also i checked, it's not working 
> 2. I see you use lowercase for `in_loc` - does it work as expected?
in_loc working as expected.

**Comment by mukeshsah08** [comment]
@lptn Could you please review and merge the MR, So I can use the latest version.

Thanks!

**Comment by mukeshsah08** [comment]
@lptn 

Have you tested how yahoo works with allDay events? – You have removed a hack, don't we need it anymore?
>> Currently Yahoo does not support allDay feature since they have removed dur, also i checked, it's not working
I see you use lowercase for in_loc - does it work as expected?
>> in_loc  is working as expected.

**Comment by lptn** [comment]
@mukeshsah08 
>Currently Yahoo does not support allDay feature since they have removed dur, also i checked, it's not working

but we have an API to set allDay event in this package, means we should use a hack to support it. Package users don't know what Yahoo supports, we should mimic supporting of this, this is why we had this hack

**Comment by mukeshsah08** [comment]
@lptn , If we will add pass dur=allday, then other event fields are getting empty, because we are not passing ET, 
So we also have to pass ET to avoid the problem.

https://calendar.yahoo.com/?v=60&view=d&type=20&ST=20210417T091111Z&dur=allday&TITLE=New%20Events&DESC=Event%20Link%3A%20http%3A%2F%2Flocal.bayer.com%2Fnew-events&in_loc=123%20test

**Comment by mukeshsah08** [comment]
Incorrect (without ET):
Screenshot 2021-04-13 at 4 16 04 PM



Correct(with ET):  
Screenshot 2021-04-13 at 4 15 45 PM

**Comment by lptn** [comment]
Sorry for not being clean at this step. 

I meant, if someone creates allDay event using syntax like this:

```php
Link:: createAllDay('event', new \DateTime(), 1);
```

it should generate a valid URL to add such event. How it works now?

**Comment by mukeshsah08** [comment]
I have followed  https://www.addevent.com and found, 
FOR for all day event, we can use pass DUR like **ST=20210414&ET=20210415&DUR=allday**
https://calendar.yahoo.com/?v=60&view=d&type=20&TITLE=Test%20event1&ST=20210414&ET=20210415&DUR=allday&DESC=testing&in_loc=123%20test. and it's working
Screenshot 2021-04-13 at 4 39 29 PM


I am updating MR.

**Comment by mukeshsah08** [comment]
@lptn,  I have fixed the all day events for yahoo. Please review MR.

**Review by lptn — APPROVED** [review]
@mukeshsah08 

ok, thanks for your work! I'll apply latest improvements and release it soon

**Comment by mukeshsah08** [comment]
Thanks @lptn !

**Pull request merged**
