### PR TITLE
Add support for outlook.office365.com ->webOffice365()

### PR DESCRIPTION
**Pull request by gulios**

### CODE REVIEW

**Comment by dravenk** [comment]
This is exactly what I need. outlook.live.com doesn't work in the company's email, so we need to use office365.com

**Comment by dravenk** [comment]
When I was testing, I sometimes lost data using office365.com, and office365.com redirected to office.com. We probably need to investigate whether office365.com or office.com supports adding calendars from url.

**Comment by dravenk** [comment]
There is no official documentation. https://github.com/InteractionDesignFoundation/add-event-to-calendar-docs/blob/main/services/outlook-web.md

**Comment by dravenk** [comment]
@gulios  I haven't been able to find a url to add a calendar to Office365, but I checked Microsoft's official documentation that the domain name used to add a calendar to outlook is outlook.office.com. Please  change outlook.office365.com to outlook.office.com.
https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/calendar-rest-operations

**Comment by gulios** [comment]
> @gulios I haven't been able to find a url to add a calendar to Office365, but I checked Microsoft's official documentation that the domain name used to add a calendar to outlook is outlook.office.com. Please change outlook.office365.com to outlook.office.com.
> https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/calendar-rest-operations

ok, tested with outlook.office.com and it works. 
I'll change this PR.

**Comment by dravenk** [comment]
@gulios [gulios](https://github.com/gulios)
Hi, I saw that the domain name of PR has not been updated. Do you still update this PR?

**Comment by gulios** [comment]
> @gulios [gulios](https://github.com/gulios)
> Hi, I saw that the domain name of PR has not been updated. Do you still update this PR?

not yet, I don't have time now for this ;( methods names should be changed too.

**Comment by dravenk** [comment]
@gulios I have been working on this feature recently. Since I cannot modify this PR, I have re-opened a PR that includes your submission, please do not mind, and thank you.
Move to
Issue discussion https://github.com/spatie/calendar-links/issues/145
PR https://github.com/spatie/calendar-links/pull/146

**Comment by lptn** [comment]
Hey @[gulios](https://github.com/gulios) and [dravenk](https://github.com/dravenk)

In v1.7 we support both https://outlook.office.com and https://outlook.live.com. Do we still need to support https://outlook.office365.com, what do you think?

**Comment by gulios** [comment]
I think outlook.office.com is fine because it works form me too.

Thank you. I'll test it when have a time.

**Comment by gulios** [comment]
but no.... ;(

it doesn't work for all account types ;( 

https://outlook.office365.com
doesn't work for personal accounts

https://outlook.office.com same....

don;t get why M$ has a problems like this ;(

@dravenk can you check it for office350 and personal accounts?

**Comment by dravenk** [comment]
> but no.... ;(
> 
> it doesn't work for all account types ;(
> 
> https://outlook.office365.com doesn't work for personal accounts
> 
> https://outlook.office.com same....
> 
> don;t get why M$ has a problems like this ;(
> 
> @dravenk can you check it for office350 and personal accounts?

Yeah. I have only the company's email using office.com, personal using outlook.com. I don't have an MS365 Personal account to test. Not found good documentation about calendar API on microsoft.com. Sorry, no helpful information.

**Comment by dravenk** [comment]
@gulios @lptn Maybe we cloud check how to add a calendar event for microsoft.com. But I don't have much time to spend on it right now.  I created an issue to talk about this feature. https://github.com/spatie/calendar-links/issues/147

**Pull request closed without merging**
